version: '3'
services:
  cog-video:
    image: llinkedlist/sorawm:latest #nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04
    container_name: sorawm_container
    ports:
      - 5344:5344
      - 8501:8501
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - ./:/workspace
      - ./.cache:/root/.cache       
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true
    working_dir: /workspace
    shm_size: '16gb'

volumes:
  huggingface_cache: