import { setRequestLocale } from 'next-intl/server';
import { routing } from '@/i18n/routing';
import { generateMetadata as genMeta } from '@/lib/metadata';
import { Link } from '@/i18n/routing';
import Footer from '@/components/Footer';
import Header from '@/components/Header';

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  return genMeta({
    title: 'Terms of Service — CleanMark',
    description: 'Terms of Service for CleanMark Gemini Watermark Remover. Free tool, no warranties, use at your own discretion.',
    path: '/terms',
    locale,
  });
}

export default async function TermsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <main className="min-h-screen bg-white">
      <Header />

      <section className="py-16 px-4">
        <div className="max-w-7xl mx-auto prose prose-gray">
          <h1>Terms of Service</h1>
          <p className="text-gray-500 text-sm">Last updated: April 2, 2026</p>

          <h2>1. Acceptance of Terms</h2>
          <p>By using CleanMark (cleanmark.org) or the CleanMark Chrome extension, you agree to these Terms of Service. If you do not agree, please do not use the service.</p>

          <h2>2. Description of Service</h2>
          <p>CleanMark provides a free browser-based tool and Chrome extension for removing watermarks from images generated by Google Gemini and Google AI Studio. All processing occurs locally in your browser.</p>

          <h2>3. Free Service</h2>
          <p>CleanMark is provided free of charge with no usage limits. We reserve the right to modify or discontinue the service at any time without notice.</p>

          <h2>4. Acceptable Use</h2>
          <p>You agree to use CleanMark only for lawful purposes and in accordance with these Terms. You are responsible for ensuring your use of the service complies with applicable laws and the terms of service of any third-party platforms (including Google Gemini and AI Studio).</p>

          <h2>5. Intellectual Property</h2>
          <p>CleanMark does not claim ownership of any images you process. You retain all rights to your images. CleanMark's code and branding are the property of their respective owners.</p>

          <h2>6. Disclaimer of Warranties</h2>
          <p>CleanMark is provided "as is" without warranties of any kind. We do not guarantee that the service will be error-free, uninterrupted, or that watermark removal will be perfect in all cases.</p>

          <h2>7. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, CleanMark shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>

          <h2>8. Changes to Terms</h2>
          <p>We may update these Terms at any time. Continued use of the service after changes constitutes acceptance of the new Terms.</p>

          <h2>9. Contact</h2>
          <p>For questions about these Terms, contact us at <a href="mailto:kuyadan136@gmail.com">kuyadan136@gmail.com</a> or via <Link href="/contact">our contact page</Link>.</p>
        </div>
      </section>

      <Footer />
    </main>
  );
}
